[colors.bright]
black = "0x4d4d4d"
blue = "0xd6acff"
cyan = "0xa4ffff"
green = "0x69ff94"
magenta = "0xff92d0"
red = "0xff6e6e"
white = "0xffffff"
yellow = "0xffffa5"

[colors.normal]
black = "0x000000"
blue = "0xbd93f9"
cyan = "0x8be9fd"
green = "0x50fa7b"
magenta = "0xff79c6"
red = "0xff5555"
white = "0xbfbfbf"
yellow = "0xf1fa8c"

[colors.primary]
background = "0x282a36"
foreground = "0xf8f8f2"

[cursor]
style = "Block"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "Fira Code NerdFont"
style = "Bold"

[font.normal]
family = "Fira Code NerdFont"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 10
y = 10
